import { Component } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  template: `
    <div class="loadingio-spinner-wedges-nv0h9vc3t5p"><div class="ldio-qmbsljadren">
      <div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div>
    </div></div>
    <style type="text/css">
      @keyframes ldio-qmbsljadren {
        0% { transform: rotate(0deg) }
        100% { transform: rotate(360deg) }
      }
      .ldio-qmbsljadren > div > div {
        transform-origin: 100px 100px;
        animation: ldio-qmbsljadren 3.0303030303030303s linear infinite;
        opacity: 0.8
      }
      .ldio-qmbsljadren > div > div > div {
        position: absolute;
        left: 28px;
        top: 28px;
        width: 72px;
        height: 72px;
        border-radius: 72px 0 0 0;
        transform-origin: 100px 100px
      }.ldio-qmbsljadren > div div:nth-child(1) {
         animation-duration: 0.7575757575757576s
       }
      .ldio-qmbsljadren > div div:nth-child(1) > div {
        background: #e15b64;
        transform: rotate(0deg);
      }.ldio-qmbsljadren > div div:nth-child(2) {
         animation-duration: 1.0101010101010102s
       }
      .ldio-qmbsljadren > div div:nth-child(2) > div {
        background: #f47e60;
        transform: rotate(0deg);
      }.ldio-qmbsljadren > div div:nth-child(3) {
         animation-duration: 1.5151515151515151s
       }
      .ldio-qmbsljadren > div div:nth-child(3) > div {
        background: #f8b26a;
        transform: rotate(0deg);
      }.ldio-qmbsljadren > div div:nth-child(4) {
         animation-duration: 3.0303030303030303s
       }
      .ldio-qmbsljadren > div div:nth-child(4) > div {
        background: #abbd81;
        transform: rotate(0deg);
      }
      .loadingio-spinner-wedges-nv0h9vc3t5p {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: rgba(255, 255, 255, 0);
      }
      .ldio-qmbsljadren {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
      }
      .ldio-qmbsljadren div { box-sizing: content-box; }
      /* generated by https://loading.io/ */
    </style>
  `
})
export class LoadingSpinnerComponent {

}
